services:
  api:
    container_name: api
    image: node:22-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: "/bin/sh -c 'npm i && npm start'"
    environment:
      - NODE_ENV=development
  db:
    container_name: db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db